# Generated by Django 5.1.4 on 2025-01-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_assigned_to_alter_ticket_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='created_by',
        ),
    ]
