# Generated by Django 5.1.4 on 2025-01-08 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_assigned_to_alter_ticket_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
