# Generated by Django 5.1.4 on 2025-01-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
